/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_BWP_UplinkCommon_H_
#define	_BWP_UplinkCommon_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BWP.h"
#include "NativeEnumerated.h"
#include "NULL.h"
#include "RACH-ConfigCommon.h"
#include "constr_CHOICE.h"
#include "PUSCH-ConfigCommon.h"
#include "PUCCH-ConfigCommon.h"
#include "MsgA-ConfigCommon-r16.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BWP_UplinkCommon__rach_ConfigCommon_PR {
	BWP_UplinkCommon__rach_ConfigCommon_PR_NOTHING,	/* No components present */
	BWP_UplinkCommon__rach_ConfigCommon_PR_release,
	BWP_UplinkCommon__rach_ConfigCommon_PR_setup
} BWP_UplinkCommon__rach_ConfigCommon_PR;
typedef enum BWP_UplinkCommon__pusch_ConfigCommon_PR {
	BWP_UplinkCommon__pusch_ConfigCommon_PR_NOTHING,	/* No components present */
	BWP_UplinkCommon__pusch_ConfigCommon_PR_release,
	BWP_UplinkCommon__pusch_ConfigCommon_PR_setup
} BWP_UplinkCommon__pusch_ConfigCommon_PR;
typedef enum BWP_UplinkCommon__pucch_ConfigCommon_PR {
	BWP_UplinkCommon__pucch_ConfigCommon_PR_NOTHING,	/* No components present */
	BWP_UplinkCommon__pucch_ConfigCommon_PR_release,
	BWP_UplinkCommon__pucch_ConfigCommon_PR_setup
} BWP_UplinkCommon__pucch_ConfigCommon_PR;
typedef enum BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR {
	BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR_NOTHING,	/* No components present */
	BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR_release,
	BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR_setup
} BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR;
typedef enum BWP_UplinkCommon__useInterlacePUCCH_PUSCH_r16 {
	BWP_UplinkCommon__useInterlacePUCCH_PUSCH_r16_enabled	= 0
} e_BWP_UplinkCommon__useInterlacePUCCH_PUSCH_r16;
typedef enum BWP_UplinkCommon__msgA_ConfigCommon_r16_PR {
	BWP_UplinkCommon__msgA_ConfigCommon_r16_PR_NOTHING,	/* No components present */
	BWP_UplinkCommon__msgA_ConfigCommon_r16_PR_release,
	BWP_UplinkCommon__msgA_ConfigCommon_r16_PR_setup
} BWP_UplinkCommon__msgA_ConfigCommon_r16_PR;

/* BWP-UplinkCommon */
typedef struct BWP_UplinkCommon {
	BWP_t	 genericParameters;
	struct BWP_UplinkCommon__rach_ConfigCommon {
		BWP_UplinkCommon__rach_ConfigCommon_PR present;
		union BWP_UplinkCommon__rach_ConfigCommon_u {
			NULL_t	 release;
			RACH_ConfigCommon_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rach_ConfigCommon;
	struct BWP_UplinkCommon__pusch_ConfigCommon {
		BWP_UplinkCommon__pusch_ConfigCommon_PR present;
		union BWP_UplinkCommon__pusch_ConfigCommon_u {
			NULL_t	 release;
			PUSCH_ConfigCommon_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pusch_ConfigCommon;
	struct BWP_UplinkCommon__pucch_ConfigCommon {
		BWP_UplinkCommon__pucch_ConfigCommon_PR present;
		union BWP_UplinkCommon__pucch_ConfigCommon_u {
			NULL_t	 release;
			PUCCH_ConfigCommon_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pucch_ConfigCommon;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct BWP_UplinkCommon__rach_ConfigCommonIAB_r16 {
		BWP_UplinkCommon__rach_ConfigCommonIAB_r16_PR present;
		union BWP_UplinkCommon__rach_ConfigCommonIAB_r16_u {
			NULL_t	 release;
			RACH_ConfigCommon_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rach_ConfigCommonIAB_r16;
	long	*useInterlacePUCCH_PUSCH_r16	/* OPTIONAL */;
	struct BWP_UplinkCommon__msgA_ConfigCommon_r16 {
		BWP_UplinkCommon__msgA_ConfigCommon_r16_PR present;
		union BWP_UplinkCommon__msgA_ConfigCommon_r16_u {
			NULL_t	 release;
			MsgA_ConfigCommon_r16_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *msgA_ConfigCommon_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BWP_UplinkCommon_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_useInterlacePUCCH_PUSCH_r16_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BWP_UplinkCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_BWP_UplinkCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_BWP_UplinkCommon_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _BWP_UplinkCommon_H_ */
#include "asn_internal.h"
