/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_CA_ParametersNRDC_v1610_H_
#define	_CA_ParametersNRDC_v1610_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode1_r16 {
	CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode1_r16_supported	= 0
} e_CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode1_r16;
typedef enum CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode2_r16 {
	CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode2_r16_supported	= 0
} e_CA_ParametersNRDC_v1610__intraFR_NR_DC_PwrSharingMode2_r16;
typedef enum CA_ParametersNRDC_v1610__intraFR_NR_DC_DynamicPwrSharing_r16 {
	CA_ParametersNRDC_v1610__intraFR_NR_DC_DynamicPwrSharing_r16_short	= 0,
	CA_ParametersNRDC_v1610__intraFR_NR_DC_DynamicPwrSharing_r16_long	= 1
} e_CA_ParametersNRDC_v1610__intraFR_NR_DC_DynamicPwrSharing_r16;
typedef enum CA_ParametersNRDC_v1610__asyncNRDC_r16 {
	CA_ParametersNRDC_v1610__asyncNRDC_r16_supported	= 0
} e_CA_ParametersNRDC_v1610__asyncNRDC_r16;

/* CA-ParametersNRDC-v1610 */
typedef struct CA_ParametersNRDC_v1610 {
	long	*intraFR_NR_DC_PwrSharingMode1_r16	/* OPTIONAL */;
	long	*intraFR_NR_DC_PwrSharingMode2_r16	/* OPTIONAL */;
	long	*intraFR_NR_DC_DynamicPwrSharing_r16	/* OPTIONAL */;
	long	*asyncNRDC_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNRDC_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_intraFR_NR_DC_PwrSharingMode1_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_intraFR_NR_DC_PwrSharingMode2_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_intraFR_NR_DC_DynamicPwrSharing_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_asyncNRDC_r16_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNRDC_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNRDC_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNRDC_v1610_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CA_ParametersNRDC_v1610_H_ */
#include "asn_internal.h"
