/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_CellAccessRelatedInfo_H_
#define	_CellAccessRelatedInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PLMN-IdentityInfoList.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellAccessRelatedInfo__cellReservedForOtherUse {
	CellAccessRelatedInfo__cellReservedForOtherUse_true	= 0
} e_CellAccessRelatedInfo__cellReservedForOtherUse;
typedef enum CellAccessRelatedInfo__cellReservedForFutureUse_r16 {
	CellAccessRelatedInfo__cellReservedForFutureUse_r16_true	= 0
} e_CellAccessRelatedInfo__cellReservedForFutureUse_r16;

/* Forward declarations */
struct NPN_IdentityInfoList_r16;

/* CellAccessRelatedInfo */
typedef struct CellAccessRelatedInfo {
	PLMN_IdentityInfoList_t	 plmn_IdentityList;
	long	*cellReservedForOtherUse	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*cellReservedForFutureUse_r16	/* OPTIONAL */;
	struct NPN_IdentityInfoList_r16	*npn_IdentityInfoList_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellAccessRelatedInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReservedForOtherUse_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReservedForFutureUse_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CellAccessRelatedInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CellAccessRelatedInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CellAccessRelatedInfo_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NPN-IdentityInfoList-r16.h"

#endif	/* _CellAccessRelatedInfo_H_ */
#include "asn_internal.h"
