/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "CodebookParameters-v1610.h"

static int
memb_NativeInteger_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NativeInteger_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NativeInteger_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NativeInteger_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_type1_SinglePanel_r16_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 7)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_type1_MultiPanel_r16_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 7)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_type2_r16_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 7)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_type2_PortSelection_r16_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 7)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_Member_constr_4 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_type1_SinglePanel_r16_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_type_type1_SinglePanel_r16_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_Member_constr_6 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_type1_MultiPanel_r16_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_type_type1_MultiPanel_r16_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_Member_constr_8 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_type2_r16_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_type_type2_r16_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_Member_constr_10 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_type2_PortSelection_r16_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_type_type2_PortSelection_r16_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_type1_SinglePanel_r16_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_memb_type1_SinglePanel_r16_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_type1_MultiPanel_r16_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_memb_type1_MultiPanel_r16_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_type2_r16_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_memb_type2_r16_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_type2_PortSelection_r16_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..7)) */};
static asn_per_constraints_t asn_PER_memb_type2_PortSelection_r16_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  7 }	/* (SIZE(1..7)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_type1_SinglePanel_r16_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_4, &asn_PER_memb_Member_constr_4,  memb_NativeInteger_constraint_3 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_type1_SinglePanel_r16_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_type1_SinglePanel_r16_specs_3 = {
	sizeof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type1_SinglePanel_r16),
	offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type1_SinglePanel_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type1_SinglePanel_r16_3 = {
	"type1-SinglePanel-r16",
	"type1-SinglePanel-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_type1_SinglePanel_r16_tags_3,
	sizeof(asn_DEF_type1_SinglePanel_r16_tags_3)
		/sizeof(asn_DEF_type1_SinglePanel_r16_tags_3[0]) - 1, /* 1 */
	asn_DEF_type1_SinglePanel_r16_tags_3,	/* Same as above */
	sizeof(asn_DEF_type1_SinglePanel_r16_tags_3)
		/sizeof(asn_DEF_type1_SinglePanel_r16_tags_3[0]), /* 2 */
	{ &asn_OER_type_type1_SinglePanel_r16_constr_3, &asn_PER_type_type1_SinglePanel_r16_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_type1_SinglePanel_r16_3,
	1,	/* Single element */
	&asn_SPC_type1_SinglePanel_r16_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_type1_MultiPanel_r16_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_6, &asn_PER_memb_Member_constr_6,  memb_NativeInteger_constraint_5 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_type1_MultiPanel_r16_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_type1_MultiPanel_r16_specs_5 = {
	sizeof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type1_MultiPanel_r16),
	offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type1_MultiPanel_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type1_MultiPanel_r16_5 = {
	"type1-MultiPanel-r16",
	"type1-MultiPanel-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_type1_MultiPanel_r16_tags_5,
	sizeof(asn_DEF_type1_MultiPanel_r16_tags_5)
		/sizeof(asn_DEF_type1_MultiPanel_r16_tags_5[0]) - 1, /* 1 */
	asn_DEF_type1_MultiPanel_r16_tags_5,	/* Same as above */
	sizeof(asn_DEF_type1_MultiPanel_r16_tags_5)
		/sizeof(asn_DEF_type1_MultiPanel_r16_tags_5[0]), /* 2 */
	{ &asn_OER_type_type1_MultiPanel_r16_constr_5, &asn_PER_type_type1_MultiPanel_r16_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_type1_MultiPanel_r16_5,
	1,	/* Single element */
	&asn_SPC_type1_MultiPanel_r16_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_type2_r16_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_8, &asn_PER_memb_Member_constr_8,  memb_NativeInteger_constraint_7 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_type2_r16_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_type2_r16_specs_7 = {
	sizeof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type2_r16),
	offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type2_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type2_r16_7 = {
	"type2-r16",
	"type2-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_type2_r16_tags_7,
	sizeof(asn_DEF_type2_r16_tags_7)
		/sizeof(asn_DEF_type2_r16_tags_7[0]) - 1, /* 1 */
	asn_DEF_type2_r16_tags_7,	/* Same as above */
	sizeof(asn_DEF_type2_r16_tags_7)
		/sizeof(asn_DEF_type2_r16_tags_7[0]), /* 2 */
	{ &asn_OER_type_type2_r16_constr_7, &asn_PER_type_type2_r16_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_type2_r16_7,
	1,	/* Single element */
	&asn_SPC_type2_r16_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_type2_PortSelection_r16_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_10, &asn_PER_memb_Member_constr_10,  memb_NativeInteger_constraint_9 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_type2_PortSelection_r16_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_type2_PortSelection_r16_specs_9 = {
	sizeof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type2_PortSelection_r16),
	offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16__type2_PortSelection_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type2_PortSelection_r16_9 = {
	"type2-PortSelection-r16",
	"type2-PortSelection-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_type2_PortSelection_r16_tags_9,
	sizeof(asn_DEF_type2_PortSelection_r16_tags_9)
		/sizeof(asn_DEF_type2_PortSelection_r16_tags_9[0]) - 1, /* 1 */
	asn_DEF_type2_PortSelection_r16_tags_9,	/* Same as above */
	sizeof(asn_DEF_type2_PortSelection_r16_tags_9)
		/sizeof(asn_DEF_type2_PortSelection_r16_tags_9[0]), /* 2 */
	{ &asn_OER_type_type2_PortSelection_r16_constr_9, &asn_PER_type_type2_PortSelection_r16_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_type2_PortSelection_r16_9,
	1,	/* Single element */
	&asn_SPC_type2_PortSelection_r16_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_supportedCSI_RS_ResourceListAlt_r16_2[] = {
	{ ATF_POINTER, 4, offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16, type1_SinglePanel_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_type1_SinglePanel_r16_3,
		0,
		{ &asn_OER_memb_type1_SinglePanel_r16_constr_3, &asn_PER_memb_type1_SinglePanel_r16_constr_3,  memb_type1_SinglePanel_r16_constraint_2 },
		0, 0, /* No default value */
		"type1-SinglePanel-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16, type1_MultiPanel_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_type1_MultiPanel_r16_5,
		0,
		{ &asn_OER_memb_type1_MultiPanel_r16_constr_5, &asn_PER_memb_type1_MultiPanel_r16_constr_5,  memb_type1_MultiPanel_r16_constraint_2 },
		0, 0, /* No default value */
		"type1-MultiPanel-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16, type2_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_type2_r16_7,
		0,
		{ &asn_OER_memb_type2_r16_constr_7, &asn_PER_memb_type2_r16_constr_7,  memb_type2_r16_constraint_2 },
		0, 0, /* No default value */
		"type2-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16, type2_PortSelection_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_type2_PortSelection_r16_9,
		0,
		{ &asn_OER_memb_type2_PortSelection_r16_constr_9, &asn_PER_memb_type2_PortSelection_r16_constr_9,  memb_type2_PortSelection_r16_constraint_2 },
		0, 0, /* No default value */
		"type2-PortSelection-r16"
		},
};
static const int asn_MAP_supportedCSI_RS_ResourceListAlt_r16_oms_2[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_supportedCSI_RS_ResourceListAlt_r16_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type1-SinglePanel-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* type1-MultiPanel-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* type2-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* type2-PortSelection-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_supportedCSI_RS_ResourceListAlt_r16_specs_2 = {
	sizeof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16),
	offsetof(struct CodebookParameters_v1610__supportedCSI_RS_ResourceListAlt_r16, _asn_ctx),
	asn_MAP_supportedCSI_RS_ResourceListAlt_r16_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_supportedCSI_RS_ResourceListAlt_r16_oms_2,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_supportedCSI_RS_ResourceListAlt_r16_2 = {
	"supportedCSI-RS-ResourceListAlt-r16",
	"supportedCSI-RS-ResourceListAlt-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2,
	sizeof(asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2)
		/sizeof(asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2[0]) - 1, /* 1 */
	asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2,	/* Same as above */
	sizeof(asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2)
		/sizeof(asn_DEF_supportedCSI_RS_ResourceListAlt_r16_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_supportedCSI_RS_ResourceListAlt_r16_2,
	4,	/* Elements count */
	&asn_SPC_supportedCSI_RS_ResourceListAlt_r16_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CodebookParameters_v1610_1[] = {
	{ ATF_POINTER, 1, offsetof(struct CodebookParameters_v1610, supportedCSI_RS_ResourceListAlt_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_supportedCSI_RS_ResourceListAlt_r16_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedCSI-RS-ResourceListAlt-r16"
		},
};
static const int asn_MAP_CodebookParameters_v1610_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_CodebookParameters_v1610_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CodebookParameters_v1610_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* supportedCSI-RS-ResourceListAlt-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_CodebookParameters_v1610_specs_1 = {
	sizeof(struct CodebookParameters_v1610),
	offsetof(struct CodebookParameters_v1610, _asn_ctx),
	asn_MAP_CodebookParameters_v1610_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_CodebookParameters_v1610_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CodebookParameters_v1610 = {
	"CodebookParameters-v1610",
	"CodebookParameters-v1610",
	&asn_OP_SEQUENCE,
	asn_DEF_CodebookParameters_v1610_tags_1,
	sizeof(asn_DEF_CodebookParameters_v1610_tags_1)
		/sizeof(asn_DEF_CodebookParameters_v1610_tags_1[0]), /* 1 */
	asn_DEF_CodebookParameters_v1610_tags_1,	/* Same as above */
	sizeof(asn_DEF_CodebookParameters_v1610_tags_1)
		/sizeof(asn_DEF_CodebookParameters_v1610_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CodebookParameters_v1610_1,
	1,	/* Elements count */
	&asn_SPC_CodebookParameters_v1610_specs_1	/* Additional specs */
};

