/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "CSI-SemiPersistentOnPUSCH-TriggerState.h"

asn_TYPE_member_t asn_MBR_CSI_SemiPersistentOnPUSCH_TriggerState_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_SemiPersistentOnPUSCH_TriggerState, associatedReportConfigInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_ReportConfigId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedReportConfigInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CSI_SemiPersistentOnPUSCH_TriggerState_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* associatedReportConfigInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_CSI_SemiPersistentOnPUSCH_TriggerState_specs_1 = {
	sizeof(struct CSI_SemiPersistentOnPUSCH_TriggerState),
	offsetof(struct CSI_SemiPersistentOnPUSCH_TriggerState, _asn_ctx),
	asn_MAP_CSI_SemiPersistentOnPUSCH_TriggerState_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState = {
	"CSI-SemiPersistentOnPUSCH-TriggerState",
	"CSI-SemiPersistentOnPUSCH-TriggerState",
	&asn_OP_SEQUENCE,
	asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1,
	sizeof(asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1)
		/sizeof(asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1[0]), /* 1 */
	asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1,	/* Same as above */
	sizeof(asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1)
		/sizeof(asn_DEF_CSI_SemiPersistentOnPUSCH_TriggerState_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CSI_SemiPersistentOnPUSCH_TriggerState_1,
	1,	/* Elements count */
	&asn_SPC_CSI_SemiPersistentOnPUSCH_TriggerState_specs_1	/* Additional specs */
};

