/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_DummyC_H_
#define	_DummyC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DummyC__maxNumberTxPortsPerResource {
	DummyC__maxNumberTxPortsPerResource_p8	= 0,
	DummyC__maxNumberTxPortsPerResource_p16	= 1,
	DummyC__maxNumberTxPortsPerResource_p32	= 2
} e_DummyC__maxNumberTxPortsPerResource;
typedef enum DummyC__supportedCodebookMode {
	DummyC__supportedCodebookMode_mode1	= 0,
	DummyC__supportedCodebookMode_mode2	= 1,
	DummyC__supportedCodebookMode_both	= 2
} e_DummyC__supportedCodebookMode;
typedef enum DummyC__supportedNumberPanels {
	DummyC__supportedNumberPanels_n2	= 0,
	DummyC__supportedNumberPanels_n4	= 1
} e_DummyC__supportedNumberPanels;

/* DummyC */
typedef struct DummyC {
	long	 maxNumberTxPortsPerResource;
	long	 maxNumberResources;
	long	 totalNumberTxPorts;
	long	 supportedCodebookMode;
	long	 supportedNumberPanels;
	long	 maxNumberCSI_RS_PerResourceSet;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DummyC_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_maxNumberTxPortsPerResource_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_supportedCodebookMode_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_supportedNumberPanels_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DummyC;
extern asn_SEQUENCE_specifics_t asn_SPC_DummyC_specs_1;
extern asn_TYPE_member_t asn_MBR_DummyC_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _DummyC_H_ */
#include "asn_internal.h"
