/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_EthernetHeaderCompression_r16_H_
#define	_EthernetHeaderCompression_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EthernetHeaderCompression_r16__ehc_Common_r16__ehc_CID_Length_r16 {
	EthernetHeaderCompression_r16__ehc_Common_r16__ehc_CID_Length_r16_bits7	= 0,
	EthernetHeaderCompression_r16__ehc_Common_r16__ehc_CID_Length_r16_bits15	= 1
} e_EthernetHeaderCompression_r16__ehc_Common_r16__ehc_CID_Length_r16;
typedef enum EthernetHeaderCompression_r16__ehc_Downlink_r16__drb_ContinueEHC_DL_r16 {
	EthernetHeaderCompression_r16__ehc_Downlink_r16__drb_ContinueEHC_DL_r16_true	= 0
} e_EthernetHeaderCompression_r16__ehc_Downlink_r16__drb_ContinueEHC_DL_r16;
typedef enum EthernetHeaderCompression_r16__ehc_Uplink_r16__drb_ContinueEHC_UL_r16 {
	EthernetHeaderCompression_r16__ehc_Uplink_r16__drb_ContinueEHC_UL_r16_true	= 0
} e_EthernetHeaderCompression_r16__ehc_Uplink_r16__drb_ContinueEHC_UL_r16;

/* EthernetHeaderCompression-r16 */
typedef struct EthernetHeaderCompression_r16 {
	struct EthernetHeaderCompression_r16__ehc_Common_r16 {
		long	 ehc_CID_Length_r16;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ehc_Common_r16;
	struct EthernetHeaderCompression_r16__ehc_Downlink_r16 {
		long	*drb_ContinueEHC_DL_r16	/* OPTIONAL */;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ehc_Downlink_r16;
	struct EthernetHeaderCompression_r16__ehc_Uplink_r16 {
		long	 maxCID_EHC_UL_r16;
		long	*drb_ContinueEHC_UL_r16	/* OPTIONAL */;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ehc_Uplink_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EthernetHeaderCompression_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ehc_CID_Length_r16_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_drb_ContinueEHC_DL_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_drb_ContinueEHC_UL_r16_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_EthernetHeaderCompression_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_EthernetHeaderCompression_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_EthernetHeaderCompression_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EthernetHeaderCompression_r16_H_ */
#include "asn_internal.h"
