/*
 * Copyright 2020-2021 Telecom Paris
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -no-gen-example`
 */

#include "EUTRA-PresenceAntennaPort1.h"

/*
 * This type is implemented using BOOLEAN,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_EUTRA_PresenceAntennaPort1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (1 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EUTRA_PresenceAntennaPort1 = {
	"EUTRA-PresenceAntennaPort1",
	"EUTRA-PresenceAntennaPort1",
	&asn_OP_BOOLEAN,
	asn_DEF_EUTRA_PresenceAntennaPort1_tags_1,
	sizeof(asn_DEF_EUTRA_PresenceAntennaPort1_tags_1)
		/sizeof(asn_DEF_EUTRA_PresenceAntennaPort1_tags_1[0]), /* 1 */
	asn_DEF_EUTRA_PresenceAntennaPort1_tags_1,	/* Same as above */
	sizeof(asn_DEF_EUTRA_PresenceAntennaPort1_tags_1)
		/sizeof(asn_DEF_EUTRA_PresenceAntennaPort1_tags_1[0]), /* 1 */
	{ 0, 0, BOOLEAN_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

