/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_EventType_r16_H_
#define	_EventType_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "MeasTriggerQuantity.h"
#include "Hysteresis.h"
#include "TimeToTrigger.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventType_r16_PR {
	EventType_r16_PR_NOTHING,	/* No components present */
	EventType_r16_PR_outOfCoverage,
	EventType_r16_PR_eventL1
	/* Extensions may appear below */
	
} EventType_r16_PR;

/* EventType-r16 */
typedef struct EventType_r16 {
	EventType_r16_PR present;
	union EventType_r16_u {
		NULL_t	 outOfCoverage;
		struct EventType_r16__eventL1 {
			MeasTriggerQuantity_t	 l1_Threshold;
			Hysteresis_t	 hysteresis;
			TimeToTrigger_t	 timeToTrigger;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} eventL1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventType_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventType_r16;
extern asn_CHOICE_specifics_t asn_SPC_EventType_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_EventType_r16_1[2];
extern asn_per_constraints_t asn_PER_type_EventType_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _EventType_r16_H_ */
#include "asn_internal.h"
