/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "EventTriggerConfigNR-SL-r16.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_eventId_r16_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eventId_r16_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_reportAmount_r16_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_reportAmount_r16_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_eventC1_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC1, c1_Threshold_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CBR_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"c1-Threshold-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC1, hysteresis_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC1, timeToTrigger_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_eventC1_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventC1_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c1-Threshold-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventC1_specs_3 = {
	sizeof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC1),
	offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC1, _asn_ctx),
	asn_MAP_eventC1_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventC1_3 = {
	"eventC1",
	"eventC1",
	&asn_OP_SEQUENCE,
	asn_DEF_eventC1_tags_3,
	sizeof(asn_DEF_eventC1_tags_3)
		/sizeof(asn_DEF_eventC1_tags_3[0]) - 1, /* 1 */
	asn_DEF_eventC1_tags_3,	/* Same as above */
	sizeof(asn_DEF_eventC1_tags_3)
		/sizeof(asn_DEF_eventC1_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventC1_3,
	3,	/* Elements count */
	&asn_SPC_eventC1_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventC2_r16_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC2_r16, c2_Threshold_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CBR_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"c2-Threshold-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC2_r16, hysteresis_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC2_r16, timeToTrigger_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_eventC2_r16_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventC2_r16_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c2-Threshold-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventC2_r16_specs_7 = {
	sizeof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC2_r16),
	offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16__eventC2_r16, _asn_ctx),
	asn_MAP_eventC2_r16_tag2el_7,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventC2_r16_7 = {
	"eventC2-r16",
	"eventC2-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_eventC2_r16_tags_7,
	sizeof(asn_DEF_eventC2_r16_tags_7)
		/sizeof(asn_DEF_eventC2_r16_tags_7[0]) - 1, /* 1 */
	asn_DEF_eventC2_r16_tags_7,	/* Same as above */
	sizeof(asn_DEF_eventC2_r16_tags_7)
		/sizeof(asn_DEF_eventC2_r16_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventC2_r16_7,
	3,	/* Elements count */
	&asn_SPC_eventC2_r16_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventId_r16_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16, choice.eventC1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_eventC1_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventC1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16, choice.eventC2_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventC2_r16_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventC2-r16"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventId_r16_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventC1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eventC2-r16 */
};
static asn_CHOICE_specifics_t asn_SPC_eventId_r16_specs_2 = {
	sizeof(struct EventTriggerConfigNR_SL_r16__eventId_r16),
	offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16, _asn_ctx),
	offsetof(struct EventTriggerConfigNR_SL_r16__eventId_r16, present),
	sizeof(((struct EventTriggerConfigNR_SL_r16__eventId_r16 *)0)->present),
	asn_MAP_eventId_r16_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventId_r16_2 = {
	"eventId-r16",
	"eventId-r16",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_eventId_r16_constr_2, &asn_PER_type_eventId_r16_constr_2, CHOICE_constraint },
	asn_MBR_eventId_r16_2,
	2,	/* Elements count */
	&asn_SPC_eventId_r16_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_reportAmount_r16_value2enum_13[] = {
	{ 0,	2,	"r1" },
	{ 1,	2,	"r2" },
	{ 2,	2,	"r4" },
	{ 3,	2,	"r8" },
	{ 4,	3,	"r16" },
	{ 5,	3,	"r32" },
	{ 6,	3,	"r64" },
	{ 7,	8,	"infinity" }
};
static const unsigned int asn_MAP_reportAmount_r16_enum2value_13[] = {
	7,	/* infinity(7) */
	0,	/* r1(0) */
	4,	/* r16(4) */
	1,	/* r2(1) */
	5,	/* r32(5) */
	2,	/* r4(2) */
	6,	/* r64(6) */
	3	/* r8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_reportAmount_r16_specs_13 = {
	asn_MAP_reportAmount_r16_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_reportAmount_r16_enum2value_13,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_reportAmount_r16_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportAmount_r16_13 = {
	"reportAmount-r16",
	"reportAmount-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_reportAmount_r16_tags_13,
	sizeof(asn_DEF_reportAmount_r16_tags_13)
		/sizeof(asn_DEF_reportAmount_r16_tags_13[0]) - 1, /* 1 */
	asn_DEF_reportAmount_r16_tags_13,	/* Same as above */
	sizeof(asn_DEF_reportAmount_r16_tags_13)
		/sizeof(asn_DEF_reportAmount_r16_tags_13[0]), /* 2 */
	{ &asn_OER_type_reportAmount_r16_constr_13, &asn_PER_type_reportAmount_r16_constr_13, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportAmount_r16_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EventTriggerConfigNR_SL_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16, eventId_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventId_r16_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventId-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16, reportInterval_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportInterval,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportInterval-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16, reportAmount_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportAmount_r16_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportAmount-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventTriggerConfigNR_SL_r16, reportQuantity_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasReportQuantity_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportQuantity-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_EventTriggerConfigNR_SL_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventTriggerConfigNR_SL_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventId-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reportInterval-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reportAmount-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* reportQuantity-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_EventTriggerConfigNR_SL_r16_specs_1 = {
	sizeof(struct EventTriggerConfigNR_SL_r16),
	offsetof(struct EventTriggerConfigNR_SL_r16, _asn_ctx),
	asn_MAP_EventTriggerConfigNR_SL_r16_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EventTriggerConfigNR_SL_r16 = {
	"EventTriggerConfigNR-SL-r16",
	"EventTriggerConfigNR-SL-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_EventTriggerConfigNR_SL_r16_tags_1,
	sizeof(asn_DEF_EventTriggerConfigNR_SL_r16_tags_1)
		/sizeof(asn_DEF_EventTriggerConfigNR_SL_r16_tags_1[0]), /* 1 */
	asn_DEF_EventTriggerConfigNR_SL_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventTriggerConfigNR_SL_r16_tags_1)
		/sizeof(asn_DEF_EventTriggerConfigNR_SL_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EventTriggerConfigNR_SL_r16_1,
	4,	/* Elements count */
	&asn_SPC_EventTriggerConfigNR_SL_r16_specs_1	/* Additional specs */
};

