/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_FDM_TDM_r16_H_
#define	_FDM_TDM_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FDM_TDM_r16__repetitionScheme_r16 {
	FDM_TDM_r16__repetitionScheme_r16_fdmSchemeA	= 0,
	FDM_TDM_r16__repetitionScheme_r16_fdmSchemeB	= 1,
	FDM_TDM_r16__repetitionScheme_r16_tdmSchemeA	= 2
} e_FDM_TDM_r16__repetitionScheme_r16;

/* FDM-TDM-r16 */
typedef struct FDM_TDM_r16 {
	long	 repetitionScheme_r16;
	long	*startingSymbolOffsetK_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FDM_TDM_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_repetitionScheme_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FDM_TDM_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_FDM_TDM_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_FDM_TDM_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FDM_TDM_r16_H_ */
#include "asn_internal.h"
