/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_FeatureSetDownlinkPerCC_v1620_H_
#define	_FeatureSetDownlinkPerCC_v1620_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FeatureSetDownlinkPerCC_v1620__supportFDM_SchemeB_r16 {
	FeatureSetDownlinkPerCC_v1620__supportFDM_SchemeB_r16_supported	= 0
} e_FeatureSetDownlinkPerCC_v1620__supportFDM_SchemeB_r16;

/* Forward declarations */
struct MultiDCI_MultiTRP_r16;

/* FeatureSetDownlinkPerCC-v1620 */
typedef struct FeatureSetDownlinkPerCC_v1620 {
	struct MultiDCI_MultiTRP_r16	*multiDCI_MultiTRP_r16	/* OPTIONAL */;
	long	*supportFDM_SchemeB_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FeatureSetDownlinkPerCC_v1620_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_supportFDM_SchemeB_r16_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FeatureSetDownlinkPerCC_v1620;
extern asn_SEQUENCE_specifics_t asn_SPC_FeatureSetDownlinkPerCC_v1620_specs_1;
extern asn_TYPE_member_t asn_MBR_FeatureSetDownlinkPerCC_v1620_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MultiDCI-MultiTRP-r16.h"

#endif	/* _FeatureSetDownlinkPerCC_v1620_H_ */
#include "asn_internal.h"
