/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "fixed_grammar.asn"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -no-gen-example`
 */

#ifndef	_FeatureSetEUTRA_UplinkId_H_
#define	_FeatureSetEUTRA_UplinkId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FeatureSetEUTRA-UplinkId */
typedef long	 FeatureSetEUTRA_UplinkId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FeatureSetEUTRA_UplinkId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FeatureSetEUTRA_UplinkId;
asn_struct_free_f FeatureSetEUTRA_UplinkId_free;
asn_struct_print_f FeatureSetEUTRA_UplinkId_print;
asn_constr_check_f FeatureSetEUTRA_UplinkId_constraint;
ber_type_decoder_f FeatureSetEUTRA_UplinkId_decode_ber;
der_type_encoder_f FeatureSetEUTRA_UplinkId_encode_der;
xer_type_decoder_f FeatureSetEUTRA_UplinkId_decode_xer;
xer_type_encoder_f FeatureSetEUTRA_UplinkId_encode_xer;
oer_type_decoder_f FeatureSetEUTRA_UplinkId_decode_oer;
oer_type_encoder_f FeatureSetEUTRA_UplinkId_encode_oer;
per_type_decoder_f FeatureSetEUTRA_UplinkId_decode_uper;
per_type_encoder_f FeatureSetEUTRA_UplinkId_encode_uper;
per_type_decoder_f FeatureSetEUTRA_UplinkId_decode_aper;
per_type_encoder_f FeatureSetEUTRA_UplinkId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FeatureSetEUTRA_UplinkId_H_ */
#include "asn_internal.h"
