/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "GuardBand-r16.h"

static int
memb_startCRB_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 274)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_nrofCRBs_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_startCRB_r16_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..274) */,
	-1};
static asn_per_constraints_t asn_PER_memb_startCRB_r16_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  274 }	/* (0..274) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_nrofCRBs_r16_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_nrofCRBs_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_GuardBand_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GuardBand_r16, startCRB_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_startCRB_r16_constr_2, &asn_PER_memb_startCRB_r16_constr_2,  memb_startCRB_r16_constraint_1 },
		0, 0, /* No default value */
		"startCRB-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GuardBand_r16, nrofCRBs_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_nrofCRBs_r16_constr_3, &asn_PER_memb_nrofCRBs_r16_constr_3,  memb_nrofCRBs_r16_constraint_1 },
		0, 0, /* No default value */
		"nrofCRBs-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_GuardBand_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GuardBand_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startCRB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nrofCRBs-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_GuardBand_r16_specs_1 = {
	sizeof(struct GuardBand_r16),
	offsetof(struct GuardBand_r16, _asn_ctx),
	asn_MAP_GuardBand_r16_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GuardBand_r16 = {
	"GuardBand-r16",
	"GuardBand-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_GuardBand_r16_tags_1,
	sizeof(asn_DEF_GuardBand_r16_tags_1)
		/sizeof(asn_DEF_GuardBand_r16_tags_1[0]), /* 1 */
	asn_DEF_GuardBand_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_GuardBand_r16_tags_1)
		/sizeof(asn_DEF_GuardBand_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GuardBand_r16_1,
	2,	/* Elements count */
	&asn_SPC_GuardBand_r16_specs_1	/* Additional specs */
};

