/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_MeasResultsPerCellIdleEUTRA_r16_H_
#define	_MeasResultsPerCellIdleEUTRA_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EUTRA-PhysCellId.h"
#include "RSRP-RangeEUTRA.h"
#include "RSRQ-RangeEUTRA-r16.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MeasResultsPerCellIdleEUTRA-r16 */
typedef struct MeasResultsPerCellIdleEUTRA_r16 {
	EUTRA_PhysCellId_t	 eutra_PhysCellId_r16;
	struct MeasResultsPerCellIdleEUTRA_r16__measIdleResultEUTRA_r16 {
		RSRP_RangeEUTRA_t	*rsrp_ResultEUTRA_r16	/* OPTIONAL */;
		RSRQ_RangeEUTRA_r16_t	*rsrq_ResultEUTRA_r16	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measIdleResultEUTRA_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultsPerCellIdleEUTRA_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultsPerCellIdleEUTRA_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultsPerCellIdleEUTRA_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultsPerCellIdleEUTRA_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasResultsPerCellIdleEUTRA_r16_H_ */
#include "asn_internal.h"
