/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_MeasResultCLI_r16_H_
#define	_MeasResultCLI_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultListSRS_RSRP_r16;
struct MeasResultListCLI_RSSI_r16;

/* MeasResultCLI-r16 */
typedef struct MeasResultCLI_r16 {
	struct MeasResultListSRS_RSRP_r16	*measResultListSRS_RSRP_r16	/* OPTIONAL */;
	struct MeasResultListCLI_RSSI_r16	*measResultListCLI_RSSI_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultCLI_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultCLI_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultCLI_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultCLI_r16_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultListSRS-RSRP-r16.h"
#include "MeasResultListCLI-RSSI-r16.h"

#endif	/* _MeasResultCLI_r16_H_ */
#include "asn_internal.h"
