/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_MsgA_DMRS_Config_r16_H_
#define	_MsgA_DMRS_Config_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MsgA_DMRS_Config_r16__msgA_DMRS_AdditionalPosition_r16 {
	MsgA_DMRS_Config_r16__msgA_DMRS_AdditionalPosition_r16_pos0	= 0,
	MsgA_DMRS_Config_r16__msgA_DMRS_AdditionalPosition_r16_pos1	= 1,
	MsgA_DMRS_Config_r16__msgA_DMRS_AdditionalPosition_r16_pos3	= 2
} e_MsgA_DMRS_Config_r16__msgA_DMRS_AdditionalPosition_r16;
typedef enum MsgA_DMRS_Config_r16__msgA_MaxLength_r16 {
	MsgA_DMRS_Config_r16__msgA_MaxLength_r16_len2	= 0
} e_MsgA_DMRS_Config_r16__msgA_MaxLength_r16;

/* MsgA-DMRS-Config-r16 */
typedef struct MsgA_DMRS_Config_r16 {
	long	*msgA_DMRS_AdditionalPosition_r16	/* OPTIONAL */;
	long	*msgA_MaxLength_r16	/* OPTIONAL */;
	long	*msgA_PUSCH_DMRS_CDM_Group_r16	/* OPTIONAL */;
	long	*msgA_PUSCH_NrofPorts_r16	/* OPTIONAL */;
	long	*msgA_ScramblingID0_r16	/* OPTIONAL */;
	long	*msgA_ScramblingID1_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MsgA_DMRS_Config_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_DMRS_AdditionalPosition_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_MaxLength_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MsgA_DMRS_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MsgA_DMRS_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MsgA_DMRS_Config_r16_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _MsgA_DMRS_Config_r16_H_ */
#include "asn_internal.h"
