/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "OverheatingAssistance.h"

static asn_TYPE_member_t asn_MBR_reducedMaxMIMO_LayersFR1_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR1, reducedMIMO_LayersFR1_DL),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_LayersDL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMIMO-LayersFR1-DL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR1, reducedMIMO_LayersFR1_UL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_LayersUL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMIMO-LayersFR1-UL"
		},
};
static const ber_tlv_tag_t asn_DEF_reducedMaxMIMO_LayersFR1_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_reducedMaxMIMO_LayersFR1_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reducedMIMO-LayersFR1-DL */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reducedMIMO-LayersFR1-UL */
};
static asn_SEQUENCE_specifics_t asn_SPC_reducedMaxMIMO_LayersFR1_specs_5 = {
	sizeof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR1),
	offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR1, _asn_ctx),
	asn_MAP_reducedMaxMIMO_LayersFR1_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reducedMaxMIMO_LayersFR1_5 = {
	"reducedMaxMIMO-LayersFR1",
	"reducedMaxMIMO-LayersFR1",
	&asn_OP_SEQUENCE,
	asn_DEF_reducedMaxMIMO_LayersFR1_tags_5,
	sizeof(asn_DEF_reducedMaxMIMO_LayersFR1_tags_5)
		/sizeof(asn_DEF_reducedMaxMIMO_LayersFR1_tags_5[0]) - 1, /* 1 */
	asn_DEF_reducedMaxMIMO_LayersFR1_tags_5,	/* Same as above */
	sizeof(asn_DEF_reducedMaxMIMO_LayersFR1_tags_5)
		/sizeof(asn_DEF_reducedMaxMIMO_LayersFR1_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_reducedMaxMIMO_LayersFR1_5,
	2,	/* Elements count */
	&asn_SPC_reducedMaxMIMO_LayersFR1_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_reducedMaxMIMO_LayersFR2_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR2, reducedMIMO_LayersFR2_DL),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_LayersDL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMIMO-LayersFR2-DL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR2, reducedMIMO_LayersFR2_UL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_LayersUL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMIMO-LayersFR2-UL"
		},
};
static const ber_tlv_tag_t asn_DEF_reducedMaxMIMO_LayersFR2_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_reducedMaxMIMO_LayersFR2_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reducedMIMO-LayersFR2-DL */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reducedMIMO-LayersFR2-UL */
};
static asn_SEQUENCE_specifics_t asn_SPC_reducedMaxMIMO_LayersFR2_specs_8 = {
	sizeof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR2),
	offsetof(struct OverheatingAssistance__reducedMaxMIMO_LayersFR2, _asn_ctx),
	asn_MAP_reducedMaxMIMO_LayersFR2_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reducedMaxMIMO_LayersFR2_8 = {
	"reducedMaxMIMO-LayersFR2",
	"reducedMaxMIMO-LayersFR2",
	&asn_OP_SEQUENCE,
	asn_DEF_reducedMaxMIMO_LayersFR2_tags_8,
	sizeof(asn_DEF_reducedMaxMIMO_LayersFR2_tags_8)
		/sizeof(asn_DEF_reducedMaxMIMO_LayersFR2_tags_8[0]) - 1, /* 1 */
	asn_DEF_reducedMaxMIMO_LayersFR2_tags_8,	/* Same as above */
	sizeof(asn_DEF_reducedMaxMIMO_LayersFR2_tags_8)
		/sizeof(asn_DEF_reducedMaxMIMO_LayersFR2_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_reducedMaxMIMO_LayersFR2_8,
	2,	/* Elements count */
	&asn_SPC_reducedMaxMIMO_LayersFR2_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_OverheatingAssistance_1[] = {
	{ ATF_POINTER, 5, offsetof(struct OverheatingAssistance, reducedMaxCCs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReducedMaxCCs_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMaxCCs"
		},
	{ ATF_POINTER, 4, offsetof(struct OverheatingAssistance, reducedMaxBW_FR1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReducedMaxBW_FRx_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMaxBW-FR1"
		},
	{ ATF_POINTER, 3, offsetof(struct OverheatingAssistance, reducedMaxBW_FR2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReducedMaxBW_FRx_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMaxBW-FR2"
		},
	{ ATF_POINTER, 2, offsetof(struct OverheatingAssistance, reducedMaxMIMO_LayersFR1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_reducedMaxMIMO_LayersFR1_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMaxMIMO-LayersFR1"
		},
	{ ATF_POINTER, 1, offsetof(struct OverheatingAssistance, reducedMaxMIMO_LayersFR2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_reducedMaxMIMO_LayersFR2_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reducedMaxMIMO-LayersFR2"
		},
};
static const int asn_MAP_OverheatingAssistance_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_OverheatingAssistance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OverheatingAssistance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reducedMaxCCs */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reducedMaxBW-FR1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reducedMaxBW-FR2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* reducedMaxMIMO-LayersFR1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* reducedMaxMIMO-LayersFR2 */
};
asn_SEQUENCE_specifics_t asn_SPC_OverheatingAssistance_specs_1 = {
	sizeof(struct OverheatingAssistance),
	offsetof(struct OverheatingAssistance, _asn_ctx),
	asn_MAP_OverheatingAssistance_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_OverheatingAssistance_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OverheatingAssistance = {
	"OverheatingAssistance",
	"OverheatingAssistance",
	&asn_OP_SEQUENCE,
	asn_DEF_OverheatingAssistance_tags_1,
	sizeof(asn_DEF_OverheatingAssistance_tags_1)
		/sizeof(asn_DEF_OverheatingAssistance_tags_1[0]), /* 1 */
	asn_DEF_OverheatingAssistance_tags_1,	/* Same as above */
	sizeof(asn_DEF_OverheatingAssistance_tags_1)
		/sizeof(asn_DEF_OverheatingAssistance_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OverheatingAssistance_1,
	5,	/* Elements count */
	&asn_SPC_OverheatingAssistance_specs_1	/* Additional specs */
};

