/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "PathlossReferenceRS-Config.h"

static asn_oer_constraints_t asn_OER_type_PathlossReferenceRS_Config_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_PathlossReferenceRS_Config_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PathlossReferenceRS_Config_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PathlossReferenceRS_Config, choice.ssb_Index),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SSB_Index,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PathlossReferenceRS_Config, choice.csi_RS_Index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NZP_CSI_RS_ResourceId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-Index"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_PathlossReferenceRS_Config_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ssb-Index */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* csi-RS-Index */
};
asn_CHOICE_specifics_t asn_SPC_PathlossReferenceRS_Config_specs_1 = {
	sizeof(struct PathlossReferenceRS_Config),
	offsetof(struct PathlossReferenceRS_Config, _asn_ctx),
	offsetof(struct PathlossReferenceRS_Config, present),
	sizeof(((struct PathlossReferenceRS_Config *)0)->present),
	asn_MAP_PathlossReferenceRS_Config_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PathlossReferenceRS_Config = {
	"PathlossReferenceRS-Config",
	"PathlossReferenceRS-Config",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_PathlossReferenceRS_Config_constr_1, &asn_PER_type_PathlossReferenceRS_Config_constr_1, CHOICE_constraint },
	asn_MBR_PathlossReferenceRS_Config_1,
	2,	/* Elements count */
	&asn_SPC_PathlossReferenceRS_Config_specs_1	/* Additional specs */
};

