/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_PerRAAttemptInfo_r16_H_
#define	_PerRAAttemptInfo_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PerRAAttemptInfo-r16 */
typedef struct PerRAAttemptInfo_r16 {
	BOOLEAN_t	*contentionDetected_r16	/* OPTIONAL */;
	BOOLEAN_t	*dlRSRPAboveThreshold_r16	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerRAAttemptInfo_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerRAAttemptInfo_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_PerRAAttemptInfo_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PerRAAttemptInfo_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PerRAAttemptInfo_r16_H_ */
#include "asn_internal.h"
