/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "PerRASSBInfo-r16.h"

static int
memb_numberOfPreamblesSentOnSSB_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 200)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_numberOfPreamblesSentOnSSB_r16_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (1..200) */,
	-1};
static asn_per_constraints_t asn_PER_memb_numberOfPreamblesSentOnSSB_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  1,  200 }	/* (1..200) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PerRASSBInfo_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PerRASSBInfo_r16, ssb_Index_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SSB_Index,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Index-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PerRASSBInfo_r16, numberOfPreamblesSentOnSSB_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_numberOfPreamblesSentOnSSB_r16_constr_3, &asn_PER_memb_numberOfPreamblesSentOnSSB_r16_constr_3,  memb_numberOfPreamblesSentOnSSB_r16_constraint_1 },
		0, 0, /* No default value */
		"numberOfPreamblesSentOnSSB-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PerRASSBInfo_r16, perRAAttemptInfoList_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PerRAAttemptInfoList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"perRAAttemptInfoList-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_PerRASSBInfo_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PerRASSBInfo_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ssb-Index-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfPreamblesSentOnSSB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* perRAAttemptInfoList-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_PerRASSBInfo_r16_specs_1 = {
	sizeof(struct PerRASSBInfo_r16),
	offsetof(struct PerRASSBInfo_r16, _asn_ctx),
	asn_MAP_PerRASSBInfo_r16_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PerRASSBInfo_r16 = {
	"PerRASSBInfo-r16",
	"PerRASSBInfo-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_PerRASSBInfo_r16_tags_1,
	sizeof(asn_DEF_PerRASSBInfo_r16_tags_1)
		/sizeof(asn_DEF_PerRASSBInfo_r16_tags_1[0]), /* 1 */
	asn_DEF_PerRASSBInfo_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_PerRASSBInfo_r16_tags_1)
		/sizeof(asn_DEF_PerRASSBInfo_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PerRASSBInfo_r16_1,
	3,	/* Elements count */
	&asn_SPC_PerRASSBInfo_r16_specs_1	/* Additional specs */
};

