/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "fixed_grammar.asn"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -no-gen-example`
 */

#ifndef	_PTRS_DensityRecommendationUL_H_
#define	_PTRS_DensityRecommendationUL_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PTRS-DensityRecommendationUL */
typedef struct PTRS_DensityRecommendationUL {
	long	 frequencyDensity1;
	long	 frequencyDensity2;
	long	 timeDensity1;
	long	 timeDensity2;
	long	 timeDensity3;
	long	 sampleDensity1;
	long	 sampleDensity2;
	long	 sampleDensity3;
	long	 sampleDensity4;
	long	 sampleDensity5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PTRS_DensityRecommendationUL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PTRS_DensityRecommendationUL;
extern asn_SEQUENCE_specifics_t asn_SPC_PTRS_DensityRecommendationUL_specs_1;
extern asn_TYPE_member_t asn_MBR_PTRS_DensityRecommendationUL_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _PTRS_DensityRecommendationUL_H_ */
#include "asn_internal.h"
