/*
 * Copyright 2020-2021 Telecom Paris
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -no-gen-example`
 */

#ifndef	_ReportConfigInterRAT_H_
#define	_ReportConfigInterRAT_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportConfigInterRAT__reportType_PR {
	ReportConfigInterRAT__reportType_PR_NOTHING,	/* No components present */
	ReportConfigInterRAT__reportType_PR_periodical,
	ReportConfigInterRAT__reportType_PR_eventTriggered,
	ReportConfigInterRAT__reportType_PR_reportCGI,
	/* Extensions may appear below */
	ReportConfigInterRAT__reportType_PR_reportSFTD
} ReportConfigInterRAT__reportType_PR;

/* Forward declarations */
struct PeriodicalReportConfigInterRAT;
struct EventTriggerConfigInterRAT;
struct ReportCGI_EUTRA;
struct ReportSFTD_EUTRA;

/* ReportConfigInterRAT */
typedef struct ReportConfigInterRAT {
	struct ReportConfigInterRAT__reportType {
		ReportConfigInterRAT__reportType_PR present;
		union ReportConfigInterRAT__reportType_u {
			struct PeriodicalReportConfigInterRAT	*periodical;
			struct EventTriggerConfigInterRAT	*eventTriggered;
			struct ReportCGI_EUTRA	*reportCGI;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			struct ReportSFTD_EUTRA	*reportSFTD;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reportType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportConfigInterRAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportConfigInterRAT;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportConfigInterRAT_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportConfigInterRAT_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PeriodicalReportConfigInterRAT.h"
#include "EventTriggerConfigInterRAT.h"
#include "ReportCGI-EUTRA.h"
#include "ReportSFTD-EUTRA.h"

#endif	/* _ReportConfigInterRAT_H_ */
#include "asn_internal.h"
