/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "RRCRelease-v1610-IEs.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_voiceFallbackIndication_r16_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_voiceFallbackIndication_r16_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_measIdleConfig_r16_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_measIdleConfig_r16_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_voiceFallbackIndication_r16_value2enum_2[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_voiceFallbackIndication_r16_enum2value_2[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_voiceFallbackIndication_r16_specs_2 = {
	asn_MAP_voiceFallbackIndication_r16_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_voiceFallbackIndication_r16_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_voiceFallbackIndication_r16_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_voiceFallbackIndication_r16_2 = {
	"voiceFallbackIndication-r16",
	"voiceFallbackIndication-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_voiceFallbackIndication_r16_tags_2,
	sizeof(asn_DEF_voiceFallbackIndication_r16_tags_2)
		/sizeof(asn_DEF_voiceFallbackIndication_r16_tags_2[0]) - 1, /* 1 */
	asn_DEF_voiceFallbackIndication_r16_tags_2,	/* Same as above */
	sizeof(asn_DEF_voiceFallbackIndication_r16_tags_2)
		/sizeof(asn_DEF_voiceFallbackIndication_r16_tags_2[0]), /* 2 */
	{ &asn_OER_type_voiceFallbackIndication_r16_constr_2, &asn_PER_type_voiceFallbackIndication_r16_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_voiceFallbackIndication_r16_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measIdleConfig_r16_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRelease_v1610_IEs__measIdleConfig_r16, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRelease_v1610_IEs__measIdleConfig_r16, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasIdleConfigDedicated_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_measIdleConfig_r16_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_measIdleConfig_r16_specs_4 = {
	sizeof(struct RRCRelease_v1610_IEs__measIdleConfig_r16),
	offsetof(struct RRCRelease_v1610_IEs__measIdleConfig_r16, _asn_ctx),
	offsetof(struct RRCRelease_v1610_IEs__measIdleConfig_r16, present),
	sizeof(((struct RRCRelease_v1610_IEs__measIdleConfig_r16 *)0)->present),
	asn_MAP_measIdleConfig_r16_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measIdleConfig_r16_4 = {
	"measIdleConfig-r16",
	"measIdleConfig-r16",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_measIdleConfig_r16_constr_4, &asn_PER_type_measIdleConfig_r16_constr_4, CHOICE_constraint },
	asn_MBR_measIdleConfig_r16_4,
	2,	/* Elements count */
	&asn_SPC_measIdleConfig_r16_specs_4	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtension_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_7 = {
	sizeof(struct RRCRelease_v1610_IEs__nonCriticalExtension),
	offsetof(struct RRCRelease_v1610_IEs__nonCriticalExtension, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_7 = {
	"nonCriticalExtension",
	"nonCriticalExtension",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtension_tags_7,
	sizeof(asn_DEF_nonCriticalExtension_tags_7)
		/sizeof(asn_DEF_nonCriticalExtension_tags_7[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtension_tags_7,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtension_tags_7)
		/sizeof(asn_DEF_nonCriticalExtension_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RRCRelease_v1610_IEs_1[] = {
	{ ATF_POINTER, 3, offsetof(struct RRCRelease_v1610_IEs, voiceFallbackIndication_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_voiceFallbackIndication_r16_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"voiceFallbackIndication-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCRelease_v1610_IEs, measIdleConfig_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_measIdleConfig_r16_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdleConfig-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCRelease_v1610_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonCriticalExtension_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtension"
		},
};
static const int asn_MAP_RRCRelease_v1610_IEs_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_RRCRelease_v1610_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCRelease_v1610_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* voiceFallbackIndication-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measIdleConfig-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_RRCRelease_v1610_IEs_specs_1 = {
	sizeof(struct RRCRelease_v1610_IEs),
	offsetof(struct RRCRelease_v1610_IEs, _asn_ctx),
	asn_MAP_RRCRelease_v1610_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RRCRelease_v1610_IEs_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCRelease_v1610_IEs = {
	"RRCRelease-v1610-IEs",
	"RRCRelease-v1610-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCRelease_v1610_IEs_tags_1,
	sizeof(asn_DEF_RRCRelease_v1610_IEs_tags_1)
		/sizeof(asn_DEF_RRCRelease_v1610_IEs_tags_1[0]), /* 1 */
	asn_DEF_RRCRelease_v1610_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCRelease_v1610_IEs_tags_1)
		/sizeof(asn_DEF_RRCRelease_v1610_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCRelease_v1610_IEs_1,
	3,	/* Elements count */
	&asn_SPC_RRCRelease_v1610_IEs_specs_1	/* Additional specs */
};

