/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "SemiStaticChannelAccessConfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_period_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_period_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_period_value2enum_2[] = {
	{ 0,	3,	"ms1" },
	{ 1,	3,	"ms2" },
	{ 2,	7,	"ms2dot5" },
	{ 3,	3,	"ms4" },
	{ 4,	3,	"ms5" },
	{ 5,	4,	"ms10" }
};
static const unsigned int asn_MAP_period_enum2value_2[] = {
	0,	/* ms1(0) */
	5,	/* ms10(5) */
	1,	/* ms2(1) */
	2,	/* ms2dot5(2) */
	3,	/* ms4(3) */
	4	/* ms5(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_period_specs_2 = {
	asn_MAP_period_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_period_enum2value_2,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_period_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_period_2 = {
	"period",
	"period",
	&asn_OP_NativeEnumerated,
	asn_DEF_period_tags_2,
	sizeof(asn_DEF_period_tags_2)
		/sizeof(asn_DEF_period_tags_2[0]) - 1, /* 1 */
	asn_DEF_period_tags_2,	/* Same as above */
	sizeof(asn_DEF_period_tags_2)
		/sizeof(asn_DEF_period_tags_2[0]), /* 2 */
	{ &asn_OER_type_period_constr_2, &asn_PER_type_period_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_period_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SemiStaticChannelAccessConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SemiStaticChannelAccessConfig, period),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_period_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"period"
		},
};
static const ber_tlv_tag_t asn_DEF_SemiStaticChannelAccessConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SemiStaticChannelAccessConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* period */
};
asn_SEQUENCE_specifics_t asn_SPC_SemiStaticChannelAccessConfig_specs_1 = {
	sizeof(struct SemiStaticChannelAccessConfig),
	offsetof(struct SemiStaticChannelAccessConfig, _asn_ctx),
	asn_MAP_SemiStaticChannelAccessConfig_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SemiStaticChannelAccessConfig = {
	"SemiStaticChannelAccessConfig",
	"SemiStaticChannelAccessConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_SemiStaticChannelAccessConfig_tags_1,
	sizeof(asn_DEF_SemiStaticChannelAccessConfig_tags_1)
		/sizeof(asn_DEF_SemiStaticChannelAccessConfig_tags_1[0]), /* 1 */
	asn_DEF_SemiStaticChannelAccessConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_SemiStaticChannelAccessConfig_tags_1)
		/sizeof(asn_DEF_SemiStaticChannelAccessConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SemiStaticChannelAccessConfig_1,
	1,	/* Elements count */
	&asn_SPC_SemiStaticChannelAccessConfig_specs_1	/* Additional specs */
};

