/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "SidelinkParametersNR-r16.h"

static int
memb_supportedBandListSidelink_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 1024)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_supportedBandListSidelink_r16_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..1024)) */};
static asn_per_constraints_t asn_PER_type_supportedBandListSidelink_r16_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 10,  10,  1,  1024 }	/* (SIZE(1..1024)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_supportedBandListSidelink_r16_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..1024)) */};
static asn_per_constraints_t asn_PER_memb_supportedBandListSidelink_r16_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 10,  10,  1,  1024 }	/* (SIZE(1..1024)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_supportedBandListSidelink_r16_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BandSidelink_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_supportedBandListSidelink_r16_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_supportedBandListSidelink_r16_specs_6 = {
	sizeof(struct SidelinkParametersNR_r16__supportedBandListSidelink_r16),
	offsetof(struct SidelinkParametersNR_r16__supportedBandListSidelink_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_supportedBandListSidelink_r16_6 = {
	"supportedBandListSidelink-r16",
	"supportedBandListSidelink-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_supportedBandListSidelink_r16_tags_6,
	sizeof(asn_DEF_supportedBandListSidelink_r16_tags_6)
		/sizeof(asn_DEF_supportedBandListSidelink_r16_tags_6[0]) - 1, /* 1 */
	asn_DEF_supportedBandListSidelink_r16_tags_6,	/* Same as above */
	sizeof(asn_DEF_supportedBandListSidelink_r16_tags_6)
		/sizeof(asn_DEF_supportedBandListSidelink_r16_tags_6[0]), /* 2 */
	{ &asn_OER_type_supportedBandListSidelink_r16_constr_6, &asn_PER_type_supportedBandListSidelink_r16_constr_6, SEQUENCE_OF_constraint },
	asn_MBR_supportedBandListSidelink_r16_6,
	1,	/* Single element */
	&asn_SPC_supportedBandListSidelink_r16_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SidelinkParametersNR_r16_1[] = {
	{ ATF_POINTER, 5, offsetof(struct SidelinkParametersNR_r16, rlc_ParametersSidelink_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLC_ParametersSidelink_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlc-ParametersSidelink-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct SidelinkParametersNR_r16, mac_ParametersSidelink_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC_ParametersSidelink_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-ParametersSidelink-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct SidelinkParametersNR_r16, fdd_Add_UE_Sidelink_Capabilities_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_SidelinkCapabilityAddXDD_Mode_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd-Add-UE-Sidelink-Capabilities-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct SidelinkParametersNR_r16, tdd_Add_UE_Sidelink_Capabilities_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_SidelinkCapabilityAddXDD_Mode_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd-Add-UE-Sidelink-Capabilities-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct SidelinkParametersNR_r16, supportedBandListSidelink_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_supportedBandListSidelink_r16_6,
		0,
		{ &asn_OER_memb_supportedBandListSidelink_r16_constr_6, &asn_PER_memb_supportedBandListSidelink_r16_constr_6,  memb_supportedBandListSidelink_r16_constraint_1 },
		0, 0, /* No default value */
		"supportedBandListSidelink-r16"
		},
};
static const int asn_MAP_SidelinkParametersNR_r16_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SidelinkParametersNR_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SidelinkParametersNR_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rlc-ParametersSidelink-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mac-ParametersSidelink-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* fdd-Add-UE-Sidelink-Capabilities-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* tdd-Add-UE-Sidelink-Capabilities-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* supportedBandListSidelink-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_SidelinkParametersNR_r16_specs_1 = {
	sizeof(struct SidelinkParametersNR_r16),
	offsetof(struct SidelinkParametersNR_r16, _asn_ctx),
	asn_MAP_SidelinkParametersNR_r16_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SidelinkParametersNR_r16_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SidelinkParametersNR_r16 = {
	"SidelinkParametersNR-r16",
	"SidelinkParametersNR-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_SidelinkParametersNR_r16_tags_1,
	sizeof(asn_DEF_SidelinkParametersNR_r16_tags_1)
		/sizeof(asn_DEF_SidelinkParametersNR_r16_tags_1[0]), /* 1 */
	asn_DEF_SidelinkParametersNR_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_SidelinkParametersNR_r16_tags_1)
		/sizeof(asn_DEF_SidelinkParametersNR_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SidelinkParametersNR_r16_1,
	5,	/* Elements count */
	&asn_SPC_SidelinkParametersNR_r16_specs_1	/* Additional specs */
};

