/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_SL_PDCP_Config_r16_H_
#define	_SL_PDCP_Config_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_PDCP_Config_r16__sl_DiscardTimer_r16 {
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms3	= 0,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms10	= 1,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms20	= 2,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms25	= 3,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms30	= 4,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms40	= 5,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms50	= 6,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms60	= 7,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms75	= 8,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms100	= 9,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms150	= 10,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms200	= 11,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms250	= 12,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms300	= 13,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms500	= 14,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms750	= 15,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_ms1500	= 16,
	SL_PDCP_Config_r16__sl_DiscardTimer_r16_infinity	= 17
} e_SL_PDCP_Config_r16__sl_DiscardTimer_r16;
typedef enum SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16 {
	SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16_len12bits	= 0,
	SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16_len18bits	= 1
} e_SL_PDCP_Config_r16__sl_PDCP_SN_Size_r16;
typedef enum SL_PDCP_Config_r16__sl_OutOfOrderDelivery {
	SL_PDCP_Config_r16__sl_OutOfOrderDelivery_true	= 0
} e_SL_PDCP_Config_r16__sl_OutOfOrderDelivery;

/* SL-PDCP-Config-r16 */
typedef struct SL_PDCP_Config_r16 {
	long	*sl_DiscardTimer_r16	/* OPTIONAL */;
	long	*sl_PDCP_SN_Size_r16	/* OPTIONAL */;
	long	*sl_OutOfOrderDelivery	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_PDCP_Config_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_DiscardTimer_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_PDCP_SN_Size_r16_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_OutOfOrderDelivery_24;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SL_PDCP_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_PDCP_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_PDCP_Config_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_PDCP_Config_r16_H_ */
#include "asn_internal.h"
