/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#include "SL-SDAP-Config-r16.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_sl_MappedQoS_FlowsList_r16_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2048)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_sl_SDAP_Header_r16_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_sl_SDAP_Header_r16_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_sl_MappedQoS_FlowsList_r16_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2048)) */};
static asn_per_constraints_t asn_PER_type_sl_MappedQoS_FlowsList_r16_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  1,  2048 }	/* (SIZE(1..2048)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sl_MappedQoS_FlowsList_r16_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2048)) */};
static asn_per_constraints_t asn_PER_memb_sl_MappedQoS_FlowsList_r16_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  1,  2048 }	/* (SIZE(1..2048)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_sl_MappedQoS_Flows_r16_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_sl_MappedQoS_Flows_r16_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_sl_CastType_r16_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_sl_CastType_r16_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_sl_SDAP_Header_r16_value2enum_2[] = {
	{ 0,	7,	"present" },
	{ 1,	6,	"absent" }
};
static const unsigned int asn_MAP_sl_SDAP_Header_r16_enum2value_2[] = {
	1,	/* absent(1) */
	0	/* present(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_sl_SDAP_Header_r16_specs_2 = {
	asn_MAP_sl_SDAP_Header_r16_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_sl_SDAP_Header_r16_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_sl_SDAP_Header_r16_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sl_SDAP_Header_r16_2 = {
	"sl-SDAP-Header-r16",
	"sl-SDAP-Header-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_sl_SDAP_Header_r16_tags_2,
	sizeof(asn_DEF_sl_SDAP_Header_r16_tags_2)
		/sizeof(asn_DEF_sl_SDAP_Header_r16_tags_2[0]) - 1, /* 1 */
	asn_DEF_sl_SDAP_Header_r16_tags_2,	/* Same as above */
	sizeof(asn_DEF_sl_SDAP_Header_r16_tags_2)
		/sizeof(asn_DEF_sl_SDAP_Header_r16_tags_2[0]), /* 2 */
	{ &asn_OER_type_sl_SDAP_Header_r16_constr_2, &asn_PER_type_sl_SDAP_Header_r16_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sl_SDAP_Header_r16_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sl_MappedQoS_FlowsList_r16_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SL_QoS_Profile_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sl_MappedQoS_FlowsList_r16_specs_7 = {
	sizeof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16__sl_MappedQoS_FlowsList_r16),
	offsetof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16__sl_MappedQoS_FlowsList_r16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sl_MappedQoS_FlowsList_r16_7 = {
	"sl-MappedQoS-FlowsList-r16",
	"sl-MappedQoS-FlowsList-r16",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7,
	sizeof(asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7)
		/sizeof(asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7[0]) - 1, /* 1 */
	asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7,	/* Same as above */
	sizeof(asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7)
		/sizeof(asn_DEF_sl_MappedQoS_FlowsList_r16_tags_7[0]), /* 2 */
	{ &asn_OER_type_sl_MappedQoS_FlowsList_r16_constr_7, &asn_PER_type_sl_MappedQoS_FlowsList_r16_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_sl_MappedQoS_FlowsList_r16_7,
	1,	/* Single element */
	&asn_SPC_sl_MappedQoS_FlowsList_r16_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sl_MappedQoS_Flows_r16_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16, choice.sl_MappedQoS_FlowsList_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_sl_MappedQoS_FlowsList_r16_7,
		0,
		{ &asn_OER_memb_sl_MappedQoS_FlowsList_r16_constr_7, &asn_PER_memb_sl_MappedQoS_FlowsList_r16_constr_7,  memb_sl_MappedQoS_FlowsList_r16_constraint_6 },
		0, 0, /* No default value */
		"sl-MappedQoS-FlowsList-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16, choice.sl_MappedQoS_FlowsListDedicated_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_MappedQoS_FlowsListDedicated_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-MappedQoS-FlowsListDedicated-r16"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_sl_MappedQoS_Flows_r16_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-MappedQoS-FlowsList-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sl-MappedQoS-FlowsListDedicated-r16 */
};
static asn_CHOICE_specifics_t asn_SPC_sl_MappedQoS_Flows_r16_specs_6 = {
	sizeof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16),
	offsetof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16, _asn_ctx),
	offsetof(struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16, present),
	sizeof(((struct SL_SDAP_Config_r16__sl_MappedQoS_Flows_r16 *)0)->present),
	asn_MAP_sl_MappedQoS_Flows_r16_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sl_MappedQoS_Flows_r16_6 = {
	"sl-MappedQoS-Flows-r16",
	"sl-MappedQoS-Flows-r16",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_sl_MappedQoS_Flows_r16_constr_6, &asn_PER_type_sl_MappedQoS_Flows_r16_constr_6, CHOICE_constraint },
	asn_MBR_sl_MappedQoS_Flows_r16_6,
	2,	/* Elements count */
	&asn_SPC_sl_MappedQoS_Flows_r16_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_sl_CastType_r16_value2enum_10[] = {
	{ 0,	9,	"broadcast" },
	{ 1,	9,	"groupcast" },
	{ 2,	7,	"unicast" },
	{ 3,	6,	"spare1" }
};
static const unsigned int asn_MAP_sl_CastType_r16_enum2value_10[] = {
	0,	/* broadcast(0) */
	1,	/* groupcast(1) */
	3,	/* spare1(3) */
	2	/* unicast(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_sl_CastType_r16_specs_10 = {
	asn_MAP_sl_CastType_r16_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_sl_CastType_r16_enum2value_10,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_sl_CastType_r16_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sl_CastType_r16_10 = {
	"sl-CastType-r16",
	"sl-CastType-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_sl_CastType_r16_tags_10,
	sizeof(asn_DEF_sl_CastType_r16_tags_10)
		/sizeof(asn_DEF_sl_CastType_r16_tags_10[0]) - 1, /* 1 */
	asn_DEF_sl_CastType_r16_tags_10,	/* Same as above */
	sizeof(asn_DEF_sl_CastType_r16_tags_10)
		/sizeof(asn_DEF_sl_CastType_r16_tags_10[0]), /* 2 */
	{ &asn_OER_type_sl_CastType_r16_constr_10, &asn_PER_type_sl_CastType_r16_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sl_CastType_r16_specs_10	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SL_SDAP_Config_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_SDAP_Config_r16, sl_SDAP_Header_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sl_SDAP_Header_r16_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-SDAP-Header-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_SDAP_Config_r16, sl_DefaultRB_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-DefaultRB-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct SL_SDAP_Config_r16, sl_MappedQoS_Flows_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_sl_MappedQoS_Flows_r16_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-MappedQoS-Flows-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_SDAP_Config_r16, sl_CastType_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sl_CastType_r16_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-CastType-r16"
		},
};
static const int asn_MAP_SL_SDAP_Config_r16_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_SL_SDAP_Config_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SL_SDAP_Config_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-SDAP-Header-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl-DefaultRB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sl-MappedQoS-Flows-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* sl-CastType-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_SL_SDAP_Config_r16_specs_1 = {
	sizeof(struct SL_SDAP_Config_r16),
	offsetof(struct SL_SDAP_Config_r16, _asn_ctx),
	asn_MAP_SL_SDAP_Config_r16_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SL_SDAP_Config_r16_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SL_SDAP_Config_r16 = {
	"SL-SDAP-Config-r16",
	"SL-SDAP-Config-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_SL_SDAP_Config_r16_tags_1,
	sizeof(asn_DEF_SL_SDAP_Config_r16_tags_1)
		/sizeof(asn_DEF_SL_SDAP_Config_r16_tags_1[0]), /* 1 */
	asn_DEF_SL_SDAP_Config_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_SL_SDAP_Config_r16_tags_1)
		/sizeof(asn_DEF_SL_SDAP_Config_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SL_SDAP_Config_r16_1,
	4,	/* Elements count */
	&asn_SPC_SL_SDAP_Config_r16_specs_1	/* Additional specs */
};

