/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "fixed_grammar.asn"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -no-gen-example`
 */

#ifndef	_SlotFormatCombinationId_H_
#define	_SlotFormatCombinationId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SlotFormatCombinationId */
typedef long	 SlotFormatCombinationId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SlotFormatCombinationId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SlotFormatCombinationId;
asn_struct_free_f SlotFormatCombinationId_free;
asn_struct_print_f SlotFormatCombinationId_print;
asn_constr_check_f SlotFormatCombinationId_constraint;
ber_type_decoder_f SlotFormatCombinationId_decode_ber;
der_type_encoder_f SlotFormatCombinationId_encode_der;
xer_type_decoder_f SlotFormatCombinationId_decode_xer;
xer_type_encoder_f SlotFormatCombinationId_encode_xer;
oer_type_decoder_f SlotFormatCombinationId_decode_oer;
oer_type_encoder_f SlotFormatCombinationId_encode_oer;
per_type_decoder_f SlotFormatCombinationId_decode_uper;
per_type_encoder_f SlotFormatCombinationId_encode_uper;
per_type_decoder_f SlotFormatCombinationId_decode_aper;
per_type_encoder_f SlotFormatCombinationId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SlotFormatCombinationId_H_ */
#include "asn_internal.h"
