/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_SpatialRelationsSRS_Pos_r16_H_
#define	_SpatialRelationsSRS_Pos_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16;
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16;
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16;
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16;
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16;
typedef enum SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16 {
	SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16_supported	= 0
} e_SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16;

/* SpatialRelationsSRS-Pos-r16 */
typedef struct SpatialRelationsSRS_Pos_r16 {
	long	*spatialRelation_SRS_PosBasedOnSSB_Serving_r16	/* OPTIONAL */;
	long	*spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16	/* OPTIONAL */;
	long	*spatialRelation_SRS_PosBasedOnPRS_Serving_r16	/* OPTIONAL */;
	long	*spatialRelation_SRS_PosBasedOnSRS_r16	/* OPTIONAL */;
	long	*spatialRelation_SRS_PosBasedOnSSB_Neigh_r16	/* OPTIONAL */;
	long	*spatialRelation_SRS_PosBasedOnPRS_Neigh_r16	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpatialRelationsSRS_Pos_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnSSB_Serving_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnPRS_Serving_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnSRS_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnSSB_Neigh_r16_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_spatialRelation_SRS_PosBasedOnPRS_Neigh_r16_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SpatialRelationsSRS_Pos_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SpatialRelationsSRS_Pos_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SpatialRelationsSRS_Pos_r16_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _SpatialRelationsSRS_Pos_r16_H_ */
#include "asn_internal.h"
