/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_SSB_PositionQCL_Relation_r16_H_
#define	_SSB_PositionQCL_Relation_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SSB_PositionQCL_Relation_r16 {
	SSB_PositionQCL_Relation_r16_n1	= 0,
	SSB_PositionQCL_Relation_r16_n2	= 1,
	SSB_PositionQCL_Relation_r16_n4	= 2,
	SSB_PositionQCL_Relation_r16_n8	= 3
} e_SSB_PositionQCL_Relation_r16;

/* SSB-PositionQCL-Relation-r16 */
typedef long	 SSB_PositionQCL_Relation_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SSB_PositionQCL_Relation_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SSB_PositionQCL_Relation_r16;
extern const asn_INTEGER_specifics_t asn_SPC_SSB_PositionQCL_Relation_r16_specs_1;
asn_struct_free_f SSB_PositionQCL_Relation_r16_free;
asn_struct_print_f SSB_PositionQCL_Relation_r16_print;
asn_constr_check_f SSB_PositionQCL_Relation_r16_constraint;
ber_type_decoder_f SSB_PositionQCL_Relation_r16_decode_ber;
der_type_encoder_f SSB_PositionQCL_Relation_r16_encode_der;
xer_type_decoder_f SSB_PositionQCL_Relation_r16_decode_xer;
xer_type_encoder_f SSB_PositionQCL_Relation_r16_encode_xer;
oer_type_decoder_f SSB_PositionQCL_Relation_r16_decode_oer;
oer_type_encoder_f SSB_PositionQCL_Relation_r16_encode_oer;
per_type_decoder_f SSB_PositionQCL_Relation_r16_decode_uper;
per_type_encoder_f SSB_PositionQCL_Relation_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SSB_PositionQCL_Relation_r16_H_ */
#include "asn_internal.h"
