/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "NR-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -pdu=all`
 */

#ifndef	_SSB_MTC3_r16_H_
#define	_SSB_MTC3_r16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_CHOICE.h"
#include "PhysCellId.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "NULL.h"
#include "SSB-ToMeasure.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SSB_MTC3_r16__periodicityAndOffset_r16_PR {
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_NOTHING,	/* No components present */
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf5_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf10_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf20_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf40_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf80_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf160_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf320_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf640_r16,
	SSB_MTC3_r16__periodicityAndOffset_r16_PR_sf1280_r16
} SSB_MTC3_r16__periodicityAndOffset_r16_PR;
typedef enum SSB_MTC3_r16__duration_r16 {
	SSB_MTC3_r16__duration_r16_sf1	= 0,
	SSB_MTC3_r16__duration_r16_sf2	= 1,
	SSB_MTC3_r16__duration_r16_sf3	= 2,
	SSB_MTC3_r16__duration_r16_sf4	= 3,
	SSB_MTC3_r16__duration_r16_sf5	= 4
} e_SSB_MTC3_r16__duration_r16;
typedef enum SSB_MTC3_r16__ssb_ToMeasure_r16_PR {
	SSB_MTC3_r16__ssb_ToMeasure_r16_PR_NOTHING,	/* No components present */
	SSB_MTC3_r16__ssb_ToMeasure_r16_PR_release,
	SSB_MTC3_r16__ssb_ToMeasure_r16_PR_setup
} SSB_MTC3_r16__ssb_ToMeasure_r16_PR;

/* SSB-MTC3-r16 */
typedef struct SSB_MTC3_r16 {
	struct SSB_MTC3_r16__periodicityAndOffset_r16 {
		SSB_MTC3_r16__periodicityAndOffset_r16_PR present;
		union SSB_MTC3_r16__periodicityAndOffset_r16_u {
			long	 sf5_r16;
			long	 sf10_r16;
			long	 sf20_r16;
			long	 sf40_r16;
			long	 sf80_r16;
			long	 sf160_r16;
			long	 sf320_r16;
			long	 sf640_r16;
			long	 sf1280_r16;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} periodicityAndOffset_r16;
	long	 duration_r16;
	struct SSB_MTC3_r16__pci_List_r16 {
		A_SEQUENCE_OF(PhysCellId_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pci_List_r16;
	struct SSB_MTC3_r16__ssb_ToMeasure_r16 {
		SSB_MTC3_r16__ssb_ToMeasure_r16_PR present;
		union SSB_MTC3_r16__ssb_ToMeasure_r16_u {
			NULL_t	 release;
			SSB_ToMeasure_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ssb_ToMeasure_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SSB_MTC3_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_duration_r16_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SSB_MTC3_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SSB_MTC3_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SSB_MTC3_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SSB_MTC3_r16_H_ */
#include "asn_internal.h"
